{{- include "kagent.validate" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.fullname" . }}-provisioning-token
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "kagent.provisioningToken is required" .Values.kagent.provisioningToken | toString | b64enc | quote }}
